- snapshots/collections-schema.yml
- src/extensions/endpoints/adoption-code/src/index.ts
- src/extensions/endpoints/adoption-code/test/index.test.ts
- src/extensions/migrations/20240423A-add-permissions-to-read-adopted-node-version.js
Part of https://github.com/jsdelivr/globalping-probe/issues/171
> feat: sync adopter probe node version with gp

- config/init.sql
- docker-compose.yml
- knexfile.js
Related to https://github.com/jsdelivr/globalping/pull/523
> refactor: rename dash DB

- pnpm-lock.yaml
- seeds/development/user-data.js
- src/extensions/token-value/package.json
- src/extensions/token-value/src/utils/token.ts
> refactor: use base32 for tokens

- Dockerfile
- pnpm-lock.yaml
- src/extensions/endpoints/credits-timeline/src/index.ts
- src/extensions/hooks/notifications-format/.gitignore
- src/extensions/hooks/notifications-format/.mocharc.json
- src/extensions/hooks/notifications-format/package-lock.json
- src/extensions/hooks/notifications-format/package.json
- src/extensions/hooks/notifications-format/src/index.ts
- src/extensions/hooks/notifications-format/test/index.test.ts
- src/extensions/hooks/notifications-format/tsconfig.json
- src/extensions/hooks/notifications-format/wallaby.js
Part of https://github.com/jsdelivr/globalping-dash/issues/3
> feat: Address FE TODO comments

- seeds/development/user-data.js
- snapshots/collections-schema.yml
- src/extensions/endpoints/adoption-code/src/repositories/directus.ts
- src/extensions/endpoints/adoption-code/test/index.test.ts
- src/extensions/migrations/20240829GP-migrate-probe-ids-to-uuid.js
Steps to apply:
- `npm run migrate`
- `npm run schema:apply`
- `npm run schema:snapshot` just to verify that everything is valid (there should be no updates in the schema file as a result)
- rebuild container to update extensions
> feat: change probe id type from number to uuid

- seeds/development/user-data.js
- src/extensions/migrations/20240829GP-migrate-probe-ids-to-uuid.js
- src/extensions/operations/adopted-probes-credits-cron-handler/src/repositories/directus.ts
- src/extensions/operations/adopted-probes-credits-cron-handler/test/api.test.ts
- src/extensions/operations/gh-webhook-handler/src/repositories/credits.ts
- src/extensions/operations/gh-webhook-handler/test/one-time.test.ts
- src/extensions/operations/gh-webhook-handler/test/recurring.test.ts
- src/extensions/operations/sponsors-cron-handler/src/repositories/directus.ts
- src/extensions/operations/sponsors-cron-handler/test/api.test.ts
Part of: https://github.com/jsdelivr/globalping-dash/issues/3
> feat: update credits messages

- snapshots/collections-schema.yml
- src/extensions/migrations/20241004GP-uniq-gp-apps-approvals.js
Part of https://github.com/jsdelivr/globalping-auth/issues/2
> feat: add apps approvals table

- .env.development.example
- .env.example
- .env.production.example
- src/extensions/hooks/sign-up/src/index.ts
- src/extensions/hooks/sign-up/test/index.test.ts
- src/extensions/migrations/20241011GP-welcome-notifications.js
Fixes https://github.com/jsdelivr/globalping-dash/issues/30
Notes:
- make sure to set `DB_CHARSET` in all .env files. Directus requires that to handle emojis.
- updated message from `you get 500 free tests` to `you have 500 free test` to not confuse that with gaining credits every hour.
> feat: welcome notification

- seeds/development/user-data.js
part of https://github.com/jsdelivr/globalping/issues/547
> feat: add globalping_client_credentials app seed

- src/extensions/endpoints/adoption-code/src/index.ts
- src/extensions/endpoints/adoption-code/src/repositories/directus.ts
- src/extensions/endpoints/adoption-code/test/index.test.ts
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/25
> fix: check for ip duplications in alt ips

- .env.development.example
- .env.e2e.example
- .env.example
- .env.production.example
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/42
E2E will pass after the merge of https://github.com/jsdelivr/globalping-dash/pull/50
> feat: send decimal as numbers

- src/extensions/hooks/sign-up/src/index.ts
- src/extensions/hooks/sign-up/test/index.test.ts
- src/extensions/migrations/20241213GP-disable-default-email-sending.js
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/44
> feat: disable default email sending

- src/extensions/hooks/sign-in/src/index.ts
- src/extensions/hooks/sign-in/test/index.test.ts
> feat: add GitHub username to cookies

- .github/workflows/e2e.yml
- Dockerfile
- docker-compose.e2e.yml
- docker-compose.yml
- pnpm-lock.yaml
- scripts/build-dash.sh
- seeds/development/user-data.js
- src/extensions/endpoints/applications/.gitignore
- src/extensions/endpoints/applications/package-lock.json
- src/extensions/endpoints/applications/package.json
- src/extensions/endpoints/applications/src/index.ts
- src/extensions/endpoints/applications/src/utils.ts
- src/extensions/endpoints/applications/tsconfig.json
- src/extensions/migration-utils.js
- test/e2e/tests/tokens.spec.ts
- test/e2e/utils.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/14
Target branch is `e2e-2` so e2e tests will fetch the same name branch from `dash-directus`.
> feat: applications table

- .env.development.example
- .env.e2e.example
- .env.example
- .env.production.example
- .github/workflows/e2e.yml
- Dockerfile
- docker-compose.e2e.yml
- docker-compose.yml
- package.json
- pnpm-lock.yaml
- scripts/build-dash.sh
- seeds/development/user-data.js
- src/extensions/endpoints/applications/.gitignore
- src/extensions/endpoints/applications/package-lock.json
- src/extensions/endpoints/applications/package.json
- src/extensions/endpoints/applications/src/index.ts
- src/extensions/endpoints/applications/src/utils.ts
- src/extensions/endpoints/applications/tsconfig.json
- src/extensions/migration-utils.js
- test/e2e/global.setup.ts
- test/e2e/tests/index.spec.ts
- test/e2e/tests/tokens.spec.ts
- test/e2e/utils.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/47
Additionally runs e2e tests with the 'globalping-dash' repo branch with the same name, if possible.
> feat: support for e2e tests in globalping-dash repo

- snapshots/collections-schema.yml
- src/extensions/lib/src/check-firmware-versions.ts
- src/extensions/migrations/20241224GP-set-offline-notifications-type.js
- src/extensions/operations/check-outdated-firmware-cron-handler/src/actions/check-outdated-firmware.ts
- src/extensions/operations/check-outdated-firmware-cron-handler/src/repositories/directus.ts
- src/extensions/operations/check-outdated-firmware-cron-handler/test/api.test.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/src/repositories/directus.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/test/api.test.ts
Fixes https://github.com/jsdelivr/globalping-dash-directus/pull/55#discussion_r1927222255
> feat: get existing notifications by type instead of subject

- snapshots/collections-schema.yml
- src/extensions/migration-utils.js
- src/extensions/migrations/20240610GP-add-permissions-to-read-credit-additions-user-id.js
- src/extensions/migrations/20240611GP-add-permissions-to-read-credit-deductions-user-id.js
- src/extensions/migrations/20240701GP-add-permissions-to-read-credits-user-id.js
- src/extensions/migrations/20240702GP-add-permissions-to-read-probes-user-id.js
- src/extensions/migrations/20240723GP-add-permissions-to-read-probes-alt-ips.js
- src/extensions/migrations/20240830GP-update-token-permissions-and-indices.js
- src/extensions/migrations/20240921GP-update-adopted-probes-read-permissions.js
- src/extensions/migrations/20240924GP-add-permissions-to-read-system-tags.js
- src/extensions/migrations/20250115GP-add-permissions-to-read-probe-hw-firmware.js
- src/extensions/migrations/20250121GP-add-permissions-to-update-public-probes-field.js
Part of https://github.com/jsdelivr/globalping/issues/541
> feat: add public_probes field to user object

- src/extensions/endpoints/adoption-code/src/index.ts
- src/extensions/endpoints/adoption-code/src/repositories/directus.ts
- src/extensions/endpoints/adoption-code/test/index.test.ts
Part of https://github.com/jsdelivr/globalping/issues/545
> feat: ignore adoption if already assigned to that user

- .env.e2e.example
- package.json
- pnpm-lock.yaml
- src/extensions/endpoints/adoption-code/package.json
- src/extensions/endpoints/adoption-code/src/repositories/directus.ts
- src/extensions/endpoints/adoption-code/test/index.test.ts
- test/e2e/tests/probes.spec.ts
Part of https://github.com/jsdelivr/globalping/issues/625
> feat: adopt user's offline probe by asn+city if possible

- test/e2e/tests/settings.spec.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/71
> test: logout e2e test

- Dockerfile
- pnpm-lock.yaml
- seeds/development/user-data.js
- snapshots/collections-schema.yml
- src/extensions/hooks/directus-users/package.json
- src/extensions/hooks/directus-users/src/index.ts
- src/extensions/hooks/directus-users/src/repositories/directus.ts
- src/extensions/hooks/directus-users/src/validate-fields.ts
- src/extensions/hooks/directus-users/test/index.test.ts
- src/extensions/hooks/sign-up/src/index.ts
- src/extensions/interfaces/tag-prefix-selector/.gitignore
- src/extensions/interfaces/tag-prefix-selector/package-lock.json
- src/extensions/interfaces/tag-prefix-selector/package.json
- src/extensions/interfaces/tag-prefix-selector/src/index.ts
- src/extensions/interfaces/tag-prefix-selector/src/interface.vue
- src/extensions/interfaces/tag-prefix-selector/src/shims.d.ts
- src/extensions/interfaces/tag-prefix-selector/tsconfig.json
- src/extensions/migrations/20250328GP-add-permissions-to-update-default-prefix.js
- src/extensions/migrations/20250329GP-fulfill-default-prefix-for-all-users.js
- src/extensions/operations/gh-webhook-handler/src/actions/created.ts
- src/extensions/operations/gh-webhook-handler/test/recurring.test.ts
- test/e2e/tests/settings.spec.ts
- test/e2e/types.ts
- test/e2e/utils.ts
Part of https://github.com/jsdelivr/globalping-dash/issues/69
> feat: add default tag prefix setting

- snapshots/collections-schema.yml
- src/extensions/endpoints/credits-timeline/src/index.ts
- src/extensions/lib/src/check-firmware-versions.ts
- src/extensions/operations/check-outdated-firmware-cron-handler/src/repositories/directus.ts
- src/extensions/operations/check-outdated-firmware-cron-handler/test/api.test.ts
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/59
> feat: outdated node notification for Docker probes

- .env.development.example
- .env.e2e.example
- scripts/auth.sh
- scripts/init.sh
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/54
> feat: improve default setup

- src/extensions/hooks/adopted-probe/src/update-with-user.ts
Needed for https://github.com/jsdelivr/globalping-dash/issues/37
> feat: do not throw when resetting default location

- .env.development.example
- .env.e2e.example
- .env.production.example
- snapshots/collections-schema.yml
- src/extensions/migration-utils/is-outdated.js
- src/extensions/migrations/20250923GP-migrate-isOutdated-col-to-triggers.js
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/129
> fix: move isOutdated from generation to triggers

- src/extensions/endpoints/adoption-code/src/index.ts
- src/extensions/endpoints/adoption-code/src/repositories/directus.ts
- src/extensions/endpoints/adoption-code/test/index.test.ts
- src/extensions/hooks/adopted-probe/src/index.ts
- src/extensions/hooks/adopted-probe/test/index.test.ts
- src/extensions/lib/src/default-probe-name.ts
- src/extensions/lib/src/reset-fields.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/src/actions/remove-expired-probes.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/src/api.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/src/repositories/directus.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/src/types.ts
- src/extensions/operations/remove-expired-adoptions-cron-handler/test/api.test.ts
- test/e2e/tests/probes.spec.ts
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/131
> fix: incorrect "probe outdated" notification sent

- .env.development.example
- .env.e2e.example
- .env.production.example
- snapshots/collections-schema.yml
- src/extensions/hooks/directus-users/src/index.ts
- src/extensions/hooks/directus-users/src/repositories/directus.ts
Fixes https://github.com/jsdelivr/globalping-dash-directus/issues/136
> feat: don't show GitHub tokens in the UI

- test/e2e/tests/dashboard-cookie.spec.ts
> test: auth cookie format
